### ISSUE TITLE
trojans

### ISSUE THREAD

**Issue by mcsmark** [anomous/RAD-Studio-XE-10.3-Windows#1]
these files all contains trojans ? isnt the soruce supposed to be published here?

**Comment by anomous** [comment]
Which scanner are you using same registration tools will be classified as PUP or malware. Try yourself to compile a small Delphi program that utilizes TNetHTTPRequest and TNetHTTPClient. This program will now also be classified as a 'trojan' by many anti-virus products due to heuristics detection. It's detecting the programs behavior and classifies there after. The utilization of TNetHTTPRequest and TNetHTTPClient could be a simple GET request for https://github.com. This is now also home compiled 'Trojan' in the eyes of antivirus products.

**Comment by mcsmark** [comment]
I use F-Secure. But all files i make with delphi are ok. i also use various net tools with udp and tcp but no problem. i am new to github but where can i ask questions? i would like my DX version keep running without running out of the free license. i do not want the hazzle of reinstalling everything.  So i am glad that you bring an alternative :-). thanks!
